.DEFAULT_GOAL := help
.PHONY: help dev worker test lint format check openapi migrate migration downgrade up down logs build clean

# Colors for terminal output
BLUE  := \033[36m
GREEN := \033[32m
RESET := \033[0m

help: ## Show this help message
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  $(BLUE)%-15s$(RESET) %s\n", $$1, $$2}'

# --- Development ---
dev: ## Run local development server with hot-reload (Granian + uvloop)
	uv run --directory services/api granian --interface asgi --loop uvloop --host 0.0.0.0 --port 8000 --reload app.main:app

worker: ## Run local background worker process with hot-reload (Taskiq)
	uv run --directory services/api taskiq worker app.core.broker:broker --fs-discover --reload

# --- Testing & Quality Assurance ---
test: ## Run unit and integration tests (pytest)
	uv run --directory services/api pytest

lint: ## Run code linter (Ruff) and type checker (Mypy)
	uv run --directory services/api ruff check .
	uv run --directory services/api mypy app tests

format: ## Format code and auto-fix linting issues (Ruff)
	uv run --directory services/api ruff format .
	uv run --directory services/api ruff check --fix .

check: lint test ## Run all checks (linter, type checker, and tests)

openapi: ## Export current FastAPI OpenAPI specification to openapi.json
	@uv run --directory services/api python -c "import json; from app.main import app; print(json.dumps(app.openapi(), indent=2))" > openapi.json
	@echo "OpenAPI schema successfully exported to openapi.json"

# --- Database Migrations (Alembic) ---
migrate: ## Apply database migrations to head
	uv run --directory services/api alembic upgrade head

migration: ## Create a new autogenerated migration (usage: make migration m="add_feature")
	@if [ -z "$(m)" ]; then echo "Error: Migration message required. Usage: make migration m=\"message\""; exit 1; fi
	uv run --directory services/api alembic revision --autogenerate -m "$(m)"

downgrade: ## Downgrade database schema by 1 revision
	uv run --directory services/api alembic downgrade -1

# --- Docker Compose ---
up: ## Start all local services in background (Traefik, Postgres, Redis, API)
	docker compose up -d

down: ## Stop and remove all running containers and networks
	docker compose down

logs: ## Tail logs for all running services
	docker compose logs -f

build: ## Rebuild Docker containers for development
	docker compose build

clean: ## Clean up Python cache and temporary build files
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type d -name ".pytest_cache" -exec rm -rf {} +
	find . -type d -name ".ruff_cache" -exec rm -rf {} +
	find . -type d -name ".mypy_cache" -exec rm -rf {} +
